### ISSUE TITLE
auto_container not working?

### ISSUE THREAD

**Issue by shakefu** [dcermak/pytest_container#179]
Seems like something internally is broken with the auto_container fixture? 
<img width="1407" alt="image" src="https://github.com/dcermak/pytest_container/assets/1046227/3bccd991-7c13-4b88-a1c1-06e97094f1a1">

Referencing the test code in the repo here, we have this configuration:
<img width="961" alt="image" src="https://github.com/dcermak/pytest_container/assets/1046227/4f2fa521-94f9-400d-bf43-94fd11f4f68d">

Is it just misconfigured or is this a bug?

**Comment by dcermak** [comment]
I am not aware of any internal breakage, we are using `pytest_container` in production all the time and I saw no issues popping up recently in **our** setup.

I have two ideas: 
1. Did you add the `pytest_generate_tests` function to `conftest.py` as indicated in the tutorial: https://dcermak.github.io/pytest_container/tutorials.html#getting-started-with-pytest-container? (Sorry, it's probably not very visible there and should be far more prominent)
2. You might want to add a `@pytest.mark.asyncio` decorator to your test function. Otherwise pytest will not execute your tests. But I doubt that's the actual issue.

Is your code public? If yes, can you share a link and I'd take a look.

**Comment by shakefu** [comment]
1. I missed that, will retry, thanks.
2. I'm using the `asyncio_mode = "auto"` which was added uh... semi-recently. 
<img width="220" alt="image" src="https://github.com/dcermak/pytest_container/assets/1046227/2c981806-9b16-4055-8c61-d26779d0456d">

**Comment by shakefu** [comment]
Looks like that resolved it. I think I just misunderstood when I saw that section of the docs, thinking it was an optional thing for generative tests, not required for the auto_container...
